# Generated by Django 4.2.1 on 2023-06-03 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadeiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_cad', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('coordenador', models.CharField(max_length=100)),
                ('nota', models.IntegerField()),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_port', models.IntegerField()),
                ('nome_utilizador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_tecn', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('descrição', models.CharField(max_length=1000)),
                ('imagem', models.CharField(max_length=100)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnologias', to='baseDados.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_proj', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=2000)),
                ('linguagem_programacao', models.CharField(max_length=10)),
                ('cadeira', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cadeira', to='baseDados.cadeiras')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='baseDados.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_licen', models.IntegerField()),
                ('nome_licenciatura', models.CharField(max_length=100)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licenciatura', to='baseDados.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='factos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_fact', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.CharField(max_length=100)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factos', to='baseDados.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='cadeiras',
            name='licneciatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadeiras', to='baseDados.licenciatura'),
        ),
    ]
