# Generated by Django 4.2.1 on 2023-06-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=500)),
                ('data', models.DateField()),
                ('likes', models.IntegerField()),
                ('areas', models.ManyToManyField(related_name='artigos', to='blog1.area')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=500)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog1.artigo')),
            ],
        ),
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('comentario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leitor', to='blog1.comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link_repo', models.CharField(max_length=500)),
                ('pythonanywhere', models.CharField(max_length=500)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog1.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area_interesse', models.CharField(max_length=100)),
                ('artigo', models.ManyToManyField(related_name='autores', to='blog1.artigo')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog1.blog')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog1.blog'),
        ),
    ]
