# Generated by Django 4.2.1 on 2023-06-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='area_interesse',
        ),
        migrations.AddField(
            model_name='autor',
            name='areas',
            field=models.ManyToManyField(related_name='areas_interesse', to='blog1.area'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='areas',
            field=models.ManyToManyField(related_name='areas', to='blog1.area'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='artigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='blog1.artigo'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='comentario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cometários', to='blog1.comentario'),
        ),
    ]
