# Generated by Django 4.2.1 on 2023-06-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_remove_autor_area_interesse_autor_areas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='artigo',
        ),
        migrations.AddField(
            model_name='artigo',
            name='autor',
            field=models.ManyToManyField(related_name='autores', to='blog1.autor'),
        ),
    ]
