# Generated by Django 4.2.1 on 2023-06-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0003_remove_autor_artigo_artigo_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='area',
        ),
    ]
