# Generated by Django 4.2.1 on 2023-06-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0005_comentario_criador_delete_leitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
