# Generated by Django 4.2.1 on 2023-06-05 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0006_alter_artigo_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
