# Generated by Django 4.2.1 on 2023-06-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0007_alter_artigo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dono',
            name='blog',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog1.blog'),
        ),
    ]
