# Generated by Django 4.2.1 on 2023-06-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0008_alter_dono_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='titulo',
        ),
    ]
